name: Sync LeetCode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate folder name
        run: |
          FOLDER_NAME=$(date +'%Y-%m-%d-%H-%M-%S')
          echo "FOLDER_NAME=$FOLDER_NAME" >> $GITHUB_ENV

      - name: Sync
        uses: joshcai/leetcode-sync@v1.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: ${{ env.FOLDER_NAME }}
